export PATH=${HOME}/.jsvu:~/.local/bin:/usr/local/opt/ccache/libexec:/usr/local/bin:/usr/local/sbin:$PATH
eval "$(/opt/homebrew/bin/brew shellenv)"

if [[ "$PROFILE" == "1" ]]; then
  zmodload zsh/zprof
  zmodload zsh/datetime

  t0=$EPOCHREALTIME
fi

export KEYTIMEOUT=10

autoload -U zutil      # [1]
autoload -U compinit   # [2]
autoload -U complist   # [3]

# either git or brew is slow here... ~500ms
#plugins=(git brew history-substring-search)

plugins=(history-substring-search)
source "$(brew --prefix zsh-syntax-highlighting)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# Set ZSH so oh-my-zsh finds its installation
ZSH=$XDG_DATA_HOME/oh-my-zsh

# !! slow 450ms :(
source $ZSH/oh-my-zsh.sh

source $XDG_DATA_HOME/my_zsh_theme.sh

# Customize to your needs...

alias sz='source ~/.zshrc'
alias ez='vim $XDG_CONFIG_HOME/zshrc'
alias ev='vim $XDG_CONFIG_HOME/nvim'

alias vim=nvim
alias :e=cd
alias g='git'
alias v='vim'
alias c='clear'
alias e='exit'
alias l='ls -la'
alias f='ls'
alias jsc='/System/Library/Frameworks/JavaScriptCore.framework/Versions/Current/Helpers/jsc'

export EDITOR=vim
export VISUAL=vim

TIMEFMT=$'\nreal\t%E\nuser\t%U\nsys\t%S'

unsetopt nomatch
unsetopt correct_all


fpath=(/usr/local/share/zsh-completions $fpath)

bindkey -v

bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down
bindkey '^R' history-incremental-search-backward

bindkey -M vicmd '^P' history-substring-search-up
bindkey -M vicmd '^N' history-substring-search-down
bindkey -M vicmd '^R' history-incremental-search-backward

bindkey -M viins 'jk' vi-cmd-mode

alias ip="ipconfig getifaddr en0 || ipconfig getifaddr en1"
alias weather='curl http://wttr.in/london?m'

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# OCaml
alias ocaml="ledit ocaml"

export LC_ALL="en_US.UTF-8"

if [[ "$PROFILE" == "1" ]]; then
  function {
      t1=$EPOCHREALTIME
      startup=$(( t1 - t0 ))
      print "Shell startup time: $startup"
  }
  unset t0
fi
