if [[ "$PROFILE" == "1" ]]; then
  zmodload zsh/zprof
  zmodload zsh/datetime

  t0=$EPOCHREALTIME
fi

export PATH=/usr/local/opt/ccache/libexec:~/devtools/arcanist/bin:~/buck/bin:/opt/facebook/bin:/usr/local/bin:/usr/local/sbin:/opt/facebook/bin:./node_modules/.bin:$PATH

export KEYTIMEOUT=1

autoload -U zutil      # [1]
autoload -U compinit   # [2]
autoload -U complist   # [3]

# either git or brew is slow here... ~500ms
#plugins=(git brew history-substring-search)

plugins=(history-substring-search)

# Set ZSH so oh-my-zsh finds its installation
ZSH=~/.oh-my-zsh

# !! slow 450ms :(
source $ZSH/oh-my-zsh.sh

source ~/.my_zsh_theme.sh

# Customize to your needs...

alias sz='source ~/.zshrc'
alias ez='vim ~/.zshrc'
alias ev='vim ~/.vimrc'
alias et='vim ~/.tmux.conf'
alias rn=react-native

alias :e=cd
alias g='git'
alias v='vim'
alias c='clear'
alias e='exit'
alias l='ls -la'
alias f='ls'
alias jsc='/System/Library/Frameworks/JavaScriptCore.framework/Versions/Current/Resources/jsc'

export EDITOR=/usr/local/bin/vim
export VISUAL=/usr/local/bin/vim

_trap_exit() { tmux kill-session -t $$; }
trap _trap_exit EXIT
if [ $TERM != 'screen-256color' ]; then
  tmux new-session -s $$;
fi

TIMEFMT=$'\nreal\t%E\nuser\t%U\nsys\t%S'

unsetopt nomatch
unsetopt correct_all


export NODE_PATH=/usr/local/share/npm/lib/node_modules
export NODE_ENV=development

fpath=(/usr/local/share/zsh-completions $fpath)
source /usr/local/opt/zsh-syntax-highlighting/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/opt/zsh-history-substring-search/zsh-history-substring-search.zsh

bindkey -v

bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down

bindkey -M vicmd '^P' history-substring-search-up
bindkey -M vicmd '^N' history-substring-search-down

alias ip="ipconfig getifaddr en0 || ipconfig getifaddr en1"
alias weather='curl http://wttr.in/london?m'

# !! brew --prefix is slow... 600ms for both calls :(
#
# export ANDROID_SDK=$(brew --prefix android-sdk)
# export ANDROID_NDK=$(brew --prefix android-ndk)
# export ANDROID_HOME=${ANDROID_SDK}
# export PATH=${PATH}:${ANDROID_SDK}/tools:${ANDROID_SDK}/platform-tools

# OPAM configuration
eval `opam config env`

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# OCaml
alias ocaml="ledit ocaml"

export LC_ALL="en_US.UTF-8"

if [[ "$PROFILE" == "1" ]]; then
  function {
      t1=$EPOCHREALTIME
      startup=$(( t1 - t0 ))
      print "Shell startup time: $startup"
  }
  unset t0
fi
