local utils = require('utils')
local map = utils.map

vim.g.mapleader = ','

map('i', 'jk', '<Esc>')

-- pane splitting shortcuts
map('n', '<leader>v', ':vs<cr>')
map('n', '<leader>s', ':sp<cr>')
map('n', '<leader>q', ':q<cr>')
map('n', '<leader>w', ':w<cr>')
map('n', '<leader>r', ':redraw!<CR>')

-- tabs shortcuts
map('n', '<leader>t', ':tabnew<cr>')
map('n', '<C-t>h', ':tabnext<cr>')
map('n', '<C-t>l', ':tabprev<cr>')
map('n', '<C-t>c', ':tabclose<cr>')
map('n', '<leader>1', ':tabnext 1<cr>')
map('n', '<leader>2', ':tabnext 2<cr>')
map('n', '<leader>3', ':tabnext 3<cr>')
map('n', '<leader>4', ':tabnext 4<cr>')
map('n', '<leader>5', ':tabnext 5<cr>')
map('n', '<leader>6', ':tabnext 6<cr>')
map('n', '<leader>7', ':tabnext 7<cr>')
map('n', '<leader>8', ':tabnext 8<cr>')
map('n', '<leader>9', ':tablast <cr>')

-- unicode
map('i', '\\forall', '∀')
map('i', '\\turnstile', '⊢')
map('i', '\\top', '⊤')
map('i', '\\bot', '⊥')
map('i', '\\sum', '∑')
map('i', '\\neg', '¬')
map('i', '\\empty', '∅')
map('i', '\\union', '∪')
map('i', '\\intersect', '∩')
map('i', '\\member', '∈')
map('i', '\\or', '∨')
map('i', '\\and', '∧')
map('i', '\\nat', 'ℕ')
map('i', '\\int', 'ℤ')

-- GREEK LETTERS

-- upper case
map('i', '\\Alpha',     'Α')
map('i', '\\Beta',      'Β')
map('i', '\\Gamma',     'Γ')
map('i', '\\Delta',     'Δ')
map('i', '\\Epsilon',   'Ε')
map('i', '\\Zeta',      'Ζ')
map('i', '\\Eta',       'Η')
map('i', '\\Theta',     'Θ')
map('i', '\\Iota',      'Ι')
map('i', '\\Kapa',      'Κ')
map('i', '\\Lambda',    'Λ')
map('i', '\\Mu',        'Μ')
map('i', '\\Nu',        'Ν')
map('i', '\\Xi',        'Ξ')
map('i', '\\Omicron',   'Ο')
map('i', '\\Pi',        'Π')
map('i', '\\Rho',       'Ρ')
map('i', '\\Sigma',     'Σ')
map('i', '\\Tau',       'Τ')
map('i', '\\Upsilon',   'Υ')
map('i', '\\Phi',       'Φ')
map('i', '\\Chi',       'Χ')
map('i', '\\Psy',       'Ψ')
map('i', '\\Omega',     'Ω')

-- lower case
map('i', '\\alpha',     'α')
map('i', '\\beta',      'β')
map('i', '\\gamma',     'γ')
map('i', '\\delta',     'δ')
map('i', '\\epsilon',   'ε')
map('i', '\\zeta',      'ζ')
map('i', '\\eta',       'η')
map('i', '\\theta',     'θ')
map('i', '\\iota',      'ι')
map('i', '\\kapa',      'κ')
map('i', '\\lambda',    'λ')
map('i', '\\mu',        'μ')
map('i', '\\nu',        'ν')
map('i', '\\xi',        'ξ')
map('i', '\\omicron',   'ο')
map('i', '\\pi',        'π')
map('i', '\\rho',       'ρ')
map('i', '\\sigma',     'σ')
map('i', '\\tau',       'τ')
map('i', '\\upsilon',   'υ')
map('i', '\\phi',       'φ')
map('i', '\\chi',       'χ')
map('i', '\\psy',       'ψ')
map('i', '\\omega',     'ω')
